import 'dart:io';
import 'package:path/path.dart' as p;

void handleInit() {
  final file = File(p.join(Directory.current.path, 'scout_config.dart'));
  const content = '''
/// Generated by scout init
/// Re-run \`scout init\` to replace this file.
class ScoutConfig {
  static const String model = "lib/src/features/features_name/data/model";
  static const String entity = "lib/src/features/features_name/domain/entity";
  static const String datasource = "lib/src/features/features_name/data/datasource";
  static const String repository = "lib/src/features/features_name/data/repository";
  static const String usecase = "lib/src/features/features_name/domain/usecase";
  static const String ui = "lib/src/features/features_name/presentation/ui";
  static const String controller = "lib/src/features/features_name/presentation/controller";
  static const String stateManagement = "provider"; 
}
''';

  if (file.existsSync()) {
    stdout.writeln('[i] scout_config.dart exists. Replacing...');
  }
  file.writeAsStringSync(content);
  stdout.writeln('[✓] scout_config.dart created/replaced');
}
